### ISSUE TITLE
Make a new release without camlp4

### ISSUE THREAD

**Issue by XVilka** [letoh/ocaml-usb#7]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). Since the project already dropped camlp4 dependency it would be good to make the release for opam as well: http://opam.ocaml.org/packages/usb/

**Comment by letoh** [comment]
Thanks for the information. Camlp4 has been removed from the dependency list in 1.3.1 release.
